### PR TITLE
Hacktoberfest Added to contributor.js

### PR DESCRIPTION
**Pull request by J3ffJessie**
Thanks for making a friendly repo for Hacktoberfest.

### CODE REVIEW

**Comment by subeshb1** [comment]
Hi @J3ffJessie,
Thanks for creating a contribution! If you want to get this point the base branch to the repository `subeshb1/developer-community-stats`

**Comment by J3ffJessie** [comment]
Apologies. Thought I went to the right one. I will push soon.

**Comment by J3ffJessie** [comment]
I’m not sure if I am doing it correctly. I followed the directions I believe. Forked, cloned, made new branch, commit and then PR to the original project. Can you provide me a better guide on what to change please?

**Comment by subeshb1** [comment]
Yes, sure @J3ffJessie. I'll be glad to help u.

Since you have already created this PR to this repo this PR can't be directed to another repository.

You will need to create a new PR to the original repo. 
Here's how to do it:

Step 1: Go to Code section of forked repo an click on Pull request below the `Code` Button besides `Compare` Button
Screen Shot 2020-10-03 at 07 50 41


Step 2: Make sure the following is branches are selected:
Screen Shot 2020-10-02 at 23 16 26

The base should be the original repository and base branch master.
The head repository should be the forked repository and the head branch `HACTORBERFEST`

Feel free to ask more if you get stuck

**Comment by J3ffJessie** [comment]
I went to the above listed area, thank you for the instructions.  I cannot however create another PR as it says the code is the same.  Should I make changes to my forked version and then create a new PR?  I apologize for adding extra work onto everything else you have going on.

**Pull request merged**
